import { NextResponse } from "next/server";
import { eq } from "drizzle-orm";
import { z } from "zod";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import {
  customerProfiles,
  invoices,
  orders,
  subscriptionEvents,
  subscriptions,
  users,
} from "@/lib/db/schema";
import { hasUsableDatabaseUrl } from "@/lib/safe-db";
import { PLANS, type Plan } from "@/lib/plans";

const schema = z.object({
  planId: z.enum(PLANS.map((p) => p.id) as [Plan["id"], ...Plan["id"][]]).default("essentials"),
  niche: z.string().optional(),
  count: z.number().min(1).max(10).default(1),
});

const SAMPLE_BUSINESSES = [
  { name: "Maya's Salon", niche: "Salon", phone: "+64 21 555 0190", website: "mayassalon.co.nz" },
  { name: "South Auckland Plumbing", niche: "Trades", phone: "+64 27 555 0102", website: "saplumbing.co.nz" },
  { name: "Lighthouse Dental", niche: "Clinic", phone: "+64 9 555 0118", website: "lighthousedental.co.nz" },
  { name: "Strand Real Estate", niche: "Real Estate", phone: "+64 21 555 0133", website: "strand.co.nz" },
  { name: "Iron Horse Gym", niche: "Gym", phone: "+64 21 555 0145", website: "ironhorse.fit" },
  { name: "Kiwi Auto Workshop", niche: "Auto", phone: "+64 21 555 0188", website: "kiwiauto.co.nz" },
  { name: "Cuba St Cafe", niche: "Cafe", phone: "+64 4 555 0177", website: "cubastcafe.co.nz" },
  { name: "Park Lane Vets", niche: "Vet", phone: "+64 9 555 0166", website: "parklanevets.co.nz" },
];

function pickName() {
  const first = ["Sarah", "James", "Aroha", "Liam", "Sophie", "Tama", "Mia", "Hemi", "Chloe", "Daniel"];
  const last = ["Walker", "Kahu", "Smith", "Patel", "Jones", "Hayes", "Ngata", "Brown", "Martin", "O'Connor"];
  return `${first[Math.floor(Math.random() * first.length)]} ${last[Math.floor(Math.random() * last.length)]}`;
}

function newOrderNumber() {
  const ts = Date.now().toString().slice(-7);
  const rand = Math.random().toString(36).slice(2, 5).toUpperCase();
  return `ARH-${ts}-${rand}`;
}

export async function POST(req: Request) {
  const session = await auth();
  if (!session?.user?.id || session.user.role !== "admin") {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }
  if (!hasUsableDatabaseUrl()) {
    return NextResponse.json({ error: "Database is not configured" }, { status: 503 });
  }

  const json = await req.json().catch(() => ({}));
  const parsed = schema.safeParse(json);
  if (!parsed.success) {
    return NextResponse.json({ error: "Invalid body", details: parsed.error.flatten() }, { status: 400 });
  }

  const plan = PLANS.find((p) => p.id === parsed.data.planId)!;
  const created: Array<{ orderNumber: string; email: string; businessName: string }> = [];

  for (let i = 0; i < parsed.data.count; i += 1) {
    const business = SAMPLE_BUSINESSES[Math.floor(Math.random() * SAMPLE_BUSINESSES.length)];
    const ts = Date.now() + i;
    const customerName = pickName();
    const email = `test+${ts}@arohacalls.test`;
    const stripeCustomerId = `cus_test_${ts}`;
    const stripeSubscriptionId = `sub_test_${ts}`;
    const stripePriceId = `price_test_${plan.id}_${ts}`;
    const orderNumber = newOrderNumber();

    const [user] = await db
      .insert(users)
      .values({
        name: customerName,
        email,
        stripeCustomerId,
        role: "customer",
      })
      .returning();

    await db.insert(customerProfiles).values({
      userId: user.id,
      businessName: business.name,
      niche: parsed.data.niche ?? business.niche,
      phoneNumber: business.phone,
      website: business.website,
      calendarConnected: Math.random() > 0.5,
      onboardingStatus: "in_progress",
      notes: `Generated by admin test-order at ${new Date().toISOString()}`,
    });

    const [subscription] = await db
      .insert(subscriptions)
      .values({
        userId: user.id,
        stripeSubscriptionId,
        stripePriceId,
        planId: plan.id,
        status: "active",
        currency: "nzd",
        amount: plan.priceNZD * 100,
        interval: "month",
        currentPeriodStart: new Date(),
        currentPeriodEnd: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        cancelAtPeriodEnd: false,
      })
      .returning();

    await db.insert(orders).values({
      orderNumber,
      userId: user.id,
      subscriptionId: subscription.id,
      planId: plan.id,
      planName: plan.name,
      customerName,
      customerEmail: email,
      businessName: business.name,
      status: "active",
      currency: "nzd",
      amount: plan.priceNZD * 100,
      stripeCheckoutSessionId: `cs_test_${ts}`,
      metadata: { simulated: true, source: "admin-test-order" },
    });

    await db.insert(invoices).values({
      userId: user.id,
      stripeInvoiceId: `in_test_${ts}`,
      stripeSubscriptionId,
      status: "paid",
      currency: "nzd",
      amountPaid: plan.priceNZD * 100,
      amountDue: 0,
      hostedInvoiceUrl: "https://dashboard.stripe.com/test/invoices",
      periodStart: new Date(),
      periodEnd: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    });

    await db.insert(subscriptionEvents).values({
      userId: user.id,
      stripeSubscriptionId,
      type: "test_signup_simulated",
      planId: plan.id,
      toStatus: "active",
      metadata: { simulated: true },
    });

    created.push({ orderNumber, email, businessName: business.name });
  }

  return NextResponse.json({ ok: true, created });
}

export async function DELETE() {
  const session = await auth();
  if (!session?.user?.id || session.user.role !== "admin") {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }
  if (!hasUsableDatabaseUrl()) {
    return NextResponse.json({ error: "Database is not configured" }, { status: 503 });
  }
  // Cascade-delete every test+@arohacalls.test user we previously generated.
  const testUsers = await db.select().from(users);
  const ids = testUsers.filter((u) => u.email.endsWith("@arohacalls.test")).map((u) => u.id);
  let removed = 0;
  for (const id of ids) {
    await db.delete(users).where(eq(users.id, id));
    removed += 1;
  }
  return NextResponse.json({ ok: true, removed });
}
